### ISSUE TITLE
Dismiss / Close Support

### ISSUE THREAD

**Issue by mikeerickson** [coderello/laraflash#1]
Nice to see a supported version return :-)

Do you have plans on adding support for dismissing (closing) messages?

**Comment by hivokas** [comment]
Please describe what do you mean by a dismissing (closing) messages?

**Comment by mikeerickson** [comment]
Add an ` X ` in upper right corner which provides users the ability to close that specific message.

**Comment by hivokas** [comment]
Honestly, I don't think that this feature should be included in the package.
You can create your custom skin with the desired appearance and use it by specifying it in the config file.

**Comment by mikeerickson** [comment]
Fair enough
