### ISSUE TITLE
Laravel 6?

### ISSUE THREAD

**Issue by WimDeMeester** [coderello/laraflash#15]
Any plans on a laravel 6 version of this package?

**Comment by hivokas** [comment]
I've published the release with Laravel 6.0 support.

**Comment by WimDeMeester** [comment]
Thanks a lot!

**Comment by WimDeMeester** [comment]
I still can not install it in laravel 6... I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for coderello/laraflash ^2.1 -> satisfiable by coderello/laraflash[2.1.0].
    - Can only install one of: laravel/framework[v6.0.3, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.0.3].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.0.3].
    - Conclusion: install laravel/framework 5.8.x-dev
    - Installation request for laravel/framework (locked at v6.0.3, required as ^6.0) -> satisfiable by laravel/framework[v6.0.3].
```

I think the problem is that you need laravelium/sitemap ^6.0 to make laraflash installable.

**Comment by eberkund** [comment]
I have the same issue

**Comment by eberkund** [comment]
@hivokas do you think you could take a look at my PR? I'm eager to use this package with Laravel 6!! :)

**Comment by hivokas** [comment]
Guys, sorry for this issue. I've accidentally added unneeded package to the list of dependencies.
I've just removed it. So the package should work now.

**Comment by WimDeMeester** [comment]
Thanks, installs without problems now!
