### ISSUE TITLE
php 7.1

### ISSUE THREAD

**Issue by jamesj2** [coderello/laraflash#18]
I'm stuck on Laravel 5.8 with PHP 7.1.  Is it possible to change the package PHP requirement from 7.2 to 7.1?  I was unable to find any issues using PHPCompatibility tester.  Latest version I can install via composer is coderello/laraflash:^1.0.

**Comment by hivokas** [comment]
Could you submit a PR?

**Comment by hivokas** [comment]
Resolved by #20
