### ISSUE TITLE
tailwind version & prefix support

### ISSUE THREAD

**Issue by Mo7sin** [coderello/laraflash#19]
Hello,

I think adding support to add user's custom **tailwind** prefix would be useful, Many users nowadays are using tailwind with a custom prefix to avoid conflict with other frameworks.

basically class name like **`bg-green-lightest`** with my own prefix would be **`tw-bg-green-lightest`** 

Also `tailwind ^1.0` has changed class names, So the current class names like **darkest**,  **darker**,  **light**,  **lightest** won't work!

Check this out [Update any usage of text/bg/border-{color} classes](https://tailwindcss.com/docs/upgrading-to-v1#1-update-any-usage-of-text-bg-border-color-classes)

**Comment by mikeerickson** [comment]
I am confused, what are you proposing? Tailwind already supports class prefixes (it has been around since early days). 

I am sure you are aware of this, this the reason for confusion.

**Comment by Mo7sin** [comment]
@mikeerickson Yeah I'm aware that tailwind supports prefix, But This package doesn't allow users to use their own tailwind prefix, check this skin file for example [left_accent_border](https://github.com/coderello/laraflash/blob/master/resources/views/components/skins/tailwind/left_accent_border.blade.php)

As you can see, there is no way for the user to apply any prefixes, I'm not sure view files can be published with this package or not!

I hope things are clear now.

EDIT: I've reinstalled the package and published its vendor files, and it's fully customizable, Sorry about that.

**Comment by Mo7sin** [comment]
After a real-world test, it turns out that it's not picking up customized views from path `resources/views/vendor/laraflash/components/skins/` is that an issue or it's intentional?

**Comment by hivokas** [comment]
@Mo7sin it is not necessary to publish and modify default skins. They are given as a quick starting point. If they don't satisfy your needs - your can easily create your own skin in `resources/views` and put its name into the config file.

For example, you could create your skin at `resources/views/partials/skin.blade.php` and specify `partials.skin` as a value of the `skin` key inside `laraflash.php` config file.

**Comment by hivokas** [comment]
@Mo7sin does it work well for you?

**Comment by Mo7sin** [comment]
@hivokas Unfortunately,  I didn't try that.

Maybe later and I will post my feedback, thank you :)
