### ISSUE TITLE
Is there a demo I can see?

### ISSUE THREAD

**Issue by sunscreem** [coderello/laraflash#2]
This looks interesting - do you have a working implementation on the front end I can have a look at?

**Comment by hivokas** [comment]
What do you mean by a working implementation? Demo project with usage of this package?

**Comment by sunscreem** [comment]
Yeah - it would be nice to see how you use it on the front end too :)

**Comment by hivokas** [comment]
It's incredibly simple. Just one line in the blade view:
`{!! laraflash()->render() !!}`

**Comment by hivokas** [comment]
If you want to change the skin, you can do it in the config file.
