### ISSUE TITLE
Undefined property error in Laravel 8

### ISSUE THREAD

**Issue by TechTailor** [coderello/laraflash#22]
After upgrading my Laravel 7.x app to Laravel 8.0 and updating laraflash to 4.0, i am getting the following error - https://flareapp.io/share/VP6N9xPJ

Would appreciate if someone can debug and find a way to resolve this issue.

-TT

**Comment by TechTailor** [comment]
Ahh just went through the laravel 8 upgrade docs and found the "Manager $app Property" has been removed from Illuminate\Support\Manager instead the $container property must be used.

**Comment by hivokas** [comment]
@TechTailor thanks a lot for reporting and analyzing the problem. I've published the `4.0.1` release with the fix.
