### ISSUE TITLE
Increase test coverage 

### ISSUE THREAD

**Issue by hivokas** [coderello/laraflash#6]

**Comment by mathiasdonoso** [comment]
I want to help with this. Do you use a tool to generate reports for your coverage?

**Comment by hivokas** [comment]
Glad to hear it. Yes, we use Scrutinizer.
Here is the link: https://scrutinizer-ci.com/g/coderello/laraflash/

**Comment by mathiasdonoso** [comment]
Thanks for your answer!

One more question...
what would be the acceptance criteria for this task? (Example: Scrutinizer test coverage >= x%?)

**Comment by mikeerickson** [comment]
Why not make it 100% since it is a new, relatively small project.

**Comment by mathiasdonoso** [comment]
ok, seem right to me too.
